// ==============================================================================
// 
//   Copyright (C) 2014-2020, GitHub/Codeplex user AlphaCentaury
//   All rights reserved.
// 
//     See 'LICENSE.MD' file (or 'license.txt' if missing) in the project root
//     for complete license information.
// 
//   http://www.alphacentaury.org/movistartv
//   https://github.com/AlphaCentaury
// 
// ==============================================================================

namespace IpTviewr.UiServices.Discovery.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ListViewManager {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ListViewManager() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IpTviewr.UiServices.Discovery.Properties.ListViewManager", typeof(ListViewManager).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel: Description.
        /// </summary>
        internal static string ColumnDescription {
            get {
                return ResourceManager.GetString("ColumnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ColumnDescriptionShort {
            get {
                return ResourceManager.GetString("ColumnDescriptionShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel: DVB type (HD/SD).
        /// </summary>
        internal static string ColumnDvbType {
            get {
                return ResourceManager.GetString("ColumnDvbType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string ColumnDvbTypeShort {
            get {
                return ResourceManager.GetString("ColumnDvbTypeShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service: Full identifier.
        /// </summary>
        internal static string ColumnFullServiceId {
            get {
                return ResourceManager.GetString("ColumnFullServiceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Id.
        /// </summary>
        internal static string ColumnFullServiceIdShort {
            get {
                return ResourceManager.GetString("ColumnFullServiceIdShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        internal static string ColumnGenre {
            get {
                return ResourceManager.GetString("ColumnGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service: Genre code.
        /// </summary>
        internal static string ColumnGenreCode {
            get {
                return ResourceManager.GetString("ColumnGenreCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre code.
        /// </summary>
        internal static string ColumnGenreCodeShort {
            get {
                return ResourceManager.GetString("ColumnGenreCodeShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        internal static string ColumnGenreShort {
            get {
                return ResourceManager.GetString("ColumnGenreShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel: Is available.
        /// </summary>
        internal static string ColumnIsActive {
            get {
                return ResourceManager.GetString("ColumnIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string ColumnIsActiveShort {
            get {
                return ResourceManager.GetString("ColumnIsActiveShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User: Show in list.
        /// </summary>
        internal static string ColumnIsEnabled {
            get {
                return ResourceManager.GetString("ColumnIsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string ColumnIsEnabledShort {
            get {
                return ResourceManager.GetString("ColumnIsEnabledShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service: Location URL address.
        /// </summary>
        internal static string ColumnLocationUrl {
            get {
                return ResourceManager.GetString("ColumnLocationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location URL.
        /// </summary>
        internal static string ColumnLocationUrlShort {
            get {
                return ResourceManager.GetString("ColumnLocationUrlShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parental lock level.
        /// </summary>
        internal static string ColumnLockLevel {
            get {
                return ResourceManager.GetString("ColumnLockLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock.
        /// </summary>
        internal static string ColumnLockLevelShort {
            get {
                return ResourceManager.GetString("ColumnLockLevelShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel: Name.
        /// </summary>
        internal static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel: Name &amp; number.
        /// </summary>
        internal static string ColumnNameAndNumber {
            get {
                return ResourceManager.GetString("ColumnNameAndNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name &amp; Ch#.
        /// </summary>
        internal static string ColumnNameAndNumberShort {
            get {
                return ResourceManager.GetString("ColumnNameAndNumberShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ColumnNameShort {
            get {
                return ResourceManager.GetString("ColumnNameShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (None).
        /// </summary>
        internal static string ColumnNone {
            get {
                return ResourceManager.GetString("ColumnNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel: Number.
        /// </summary>
        internal static string ColumnNumber {
            get {
                return ResourceManager.GetString("ColumnNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel: Number &amp; name.
        /// </summary>
        internal static string ColumnNumberAndName {
            get {
                return ResourceManager.GetString("ColumnNumberAndName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel: Number &amp; name (in new line).
        /// </summary>
        internal static string ColumnNumberAndNameCrlf {
            get {
                return ResourceManager.GetString("ColumnNumberAndNameCrlf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ch# Name.
        /// </summary>
        internal static string ColumnNumberAndNameShort {
            get {
                return ResourceManager.GetString("ColumnNumberAndNameShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        internal static string ColumnNumberShort {
            get {
                return ResourceManager.GetString("ColumnNumberShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator: Original name.
        /// </summary>
        internal static string ColumnOriginalName {
            get {
                return ResourceManager.GetString("ColumnOriginalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original name.
        /// </summary>
        internal static string ColumnOriginalNameShort {
            get {
                return ResourceManager.GetString("ColumnOriginalNameShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator: Original number.
        /// </summary>
        internal static string ColumnOriginalNumber {
            get {
                return ResourceManager.GetString("ColumnOriginalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Org#.
        /// </summary>
        internal static string ColumnOriginalNumberShort {
            get {
                return ResourceManager.GetString("ColumnOriginalNumberShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parental rating.
        /// </summary>
        internal static string ColumnParentalRating {
            get {
                return ResourceManager.GetString("ColumnParentalRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service: Parental rating code.
        /// </summary>
        internal static string ColumnParentalRatingCode {
            get {
                return ResourceManager.GetString("ColumnParentalRatingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating code.
        /// </summary>
        internal static string ColumnParentalRatingCodeShort {
            get {
                return ResourceManager.GetString("ColumnParentalRatingCodeShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        internal static string ColumnParentalRatingShort {
            get {
                return ResourceManager.GetString("ColumnParentalRatingShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service: Identifier.
        /// </summary>
        internal static string ColumnServiceId {
            get {
                return ResourceManager.GetString("ColumnServiceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string ColumnServiceIdShort {
            get {
                return ResourceManager.GetString("ColumnServiceIdShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel: Short name.
        /// </summary>
        internal static string ColumnShortName {
            get {
                return ResourceManager.GetString("ColumnShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short name.
        /// </summary>
        internal static string ColumnShortNameShort {
            get {
                return ResourceManager.GetString("ColumnShortNameShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User: Channel name.
        /// </summary>
        internal static string ColumnUserName {
            get {
                return ResourceManager.GetString("ColumnUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        internal static string ColumnUserNameShort {
            get {
                return ResourceManager.GetString("ColumnUserNameShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User: Channel number.
        /// </summary>
        internal static string ColumnUserNumber {
            get {
                return ResourceManager.GetString("ColumnUserNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usr#.
        /// </summary>
        internal static string ColumnUserNumberShort {
            get {
                return ResourceManager.GetString("ColumnUserNumberShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        internal static string NameAndNumberFormat {
            get {
                return ResourceManager.GetString("NameAndNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///{1}.
        /// </summary>
        internal static string NumberAndNameCrlfFormat {
            get {
                return ResourceManager.GetString("NumberAndNameCrlfFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string NumberAndNameFormat {
            get {
                return ResourceManager.GetString("NumberAndNameFormat", resourceCulture);
            }
        }
    }
}
