// ==============================================================================
// 
//   Copyright (C) 2014-2020, GitHub/Codeplex user AlphaCentaury
//   All rights reserved.
// 
//     See 'LICENSE.MD' file (or 'license.txt' if missing) in the project root
//     for complete license information.
// 
//   http://www.alphacentaury.org/movistartv
//   https://github.com/AlphaCentaury
// 
// ==============================================================================

namespace IpTviewr.UiServices.Discovery.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IpTviewr.UiServices.Discovery.Properties.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list has been successfully refreshed, but it is empty..
        /// </summary>
        internal static string BroadcastListRefreshEmpty {
            get {
                return ResourceManager.GetString("BroadcastListRefreshEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The channel list has been successfully refreshed..
        /// </summary>
        internal static string BroadcastListRefreshSuccess {
            get {
                return ResourceManager.GetString("BroadcastListRefreshSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to obtain the list of TV channels/services.
        /// </summary>
        internal static string BroadcastListUnableRefresh {
            get {
                return ResourceManager.GetString("BroadcastListUnableRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtaining list of TV channels/services....
        /// </summary>
        internal static string BroadcastObtainingList {
            get {
                return ResourceManager.GetString("BroadcastObtainingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing and extracting the list of TV channels/services....
        /// </summary>
        internal static string BroadcastParsingList {
            get {
                return ResourceManager.GetString("BroadcastParsingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No description is available for this TV channel/service.
        /// </summary>
        internal static string BroadcastUnknownDisplayDescription {
            get {
                return ResourceManager.GetString("BroadcastUnknownDisplayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxx.
        /// </summary>
        internal static string ChannelNumberNone {
            get {
                return ResourceManager.GetString("ChannelNumberNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown: {0}.{1}.
        /// </summary>
        internal static string FormatBroadcastUnknownDisplayName {
            get {
                return ResourceManager.GetString("FormatBroadcastUnknownDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown ({0}).
        /// </summary>
        internal static string FormatServiceTypeIdUnknown {
            get {
                return ResourceManager.GetString("FormatServiceTypeIdUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} channels have been reallocated.
        /// </summary>
        internal static string MergeResultChangedServicesCount {
            get {
                return ResourceManager.GetString("MergeResultChangedServicesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No new, discontinued or modified channels).
        /// </summary>
        internal static string MergeResultDetailsNoData {
            get {
                return ResourceManager.GetString("MergeResultDetailsNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} channels have not changed.
        /// </summary>
        internal static string MergeResultEqualServicesCount {
            get {
                return ResourceManager.GetString("MergeResultEqualServicesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} new channels.
        /// </summary>
        internal static string MergeResultNewServicesCount {
            get {
                return ResourceManager.GetString("MergeResultNewServicesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} channels have been discontinued.
        /// </summary>
        internal static string MergeResultRemovedServicesCount {
            get {
                return ResourceManager.GetString("MergeResultRemovedServicesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No channels have been reallocated.
        /// </summary>
        internal static string MergeResultZeroChangedServices {
            get {
                return ResourceManager.GetString("MergeResultZeroChangedServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All channels have changed!.
        /// </summary>
        internal static string MergeResultZeroEqualServices {
            get {
                return ResourceManager.GetString("MergeResultZeroEqualServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no new channels.
        /// </summary>
        internal static string MergeResultZeroNewServices {
            get {
                return ResourceManager.GetString("MergeResultZeroNewServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No channels have been discontinued.
        /// </summary>
        internal static string MergeResultZeroRemovedServices {
            get {
                return ResourceManager.GetString("MergeResultZeroRemovedServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Not provided&gt;.
        /// </summary>
        internal static string NotProvidedValue {
            get {
                return ResourceManager.GetString("NotProvidedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel description and data.
        /// </summary>
        internal static string Payload02DisplayName {
            get {
                return ResourceManager.GetString("Payload02DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages and channel numbers.
        /// </summary>
        internal static string Payload05DisplayName {
            get {
                return ResourceManager.GetString("Payload05DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPG data source locations.
        /// </summary>
        internal static string Payload06DisplayName {
            get {
                return ResourceManager.GetString("Payload06DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The refreshing of the list has been cancelled by the user..
        /// </summary>
        internal static string UserCancelListRefresh {
            get {
                return ResourceManager.GetString("UserCancelListRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
