// ==============================================================================
// 
//   Copyright (C) 2014-2020, GitHub/Codeplex user AlphaCentaury
//   All rights reserved.
// 
//     See 'LICENSE.MD' file (or 'license.txt' if missing) in the project root
//     for complete license information.
// 
//   http://www.alphacentaury.org/movistartv
//   https://github.com/AlphaCentaury
// 
// ==============================================================================

namespace IpTviewr.UiServices.Record.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecordChannel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecordChannel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IpTviewr.UiServices.Record.Properties.RecordChannel", typeof(RecordChannel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The extension of the file of the recording can not be empty.
        ///Please specify a file extension..
        /// </summary>
        internal static string EmptyFileExtension {
            get {
                return ResourceManager.GetString("EmptyFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the file of the recording can not be empty.
        ///Please specify a name..
        /// </summary>
        internal static string EmptyFileName {
            get {
                return ResourceManager.GetString("EmptyFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the task can not be empty.
        ///Please specify a name..
        /// </summary>
        internal static string EmptyTaskName {
            get {
                return ResourceManager.GetString("EmptyTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .ts
        ///.raw
        ///.mpg
        ///.mp2
        ///.mp4
        ///.m2ts.
        /// </summary>
        internal static string FileExtensions {
            get {
                return ResourceManager.GetString("FileExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A save location has not been selected.
        ///Please select one or browse for a folder..
        /// </summary>
        internal static string NoSaveLocation {
            get {
                return ResourceManager.GetString("NoSaveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        internal static string RecordButtonRecord {
            get {
                return ResourceManager.GetString("RecordButtonRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set schedule.
        /// </summary>
        internal static string RecordButtonSchedule {
            get {
                return ResourceManager.GetString("RecordButtonSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule....
        /// </summary>
        internal static string RecordButtonWithSettings {
            get {
                return ResourceManager.GetString("RecordButtonWithSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Custom location&gt;.
        /// </summary>
        internal static string SaveCustomLocation {
            get {
                return ResourceManager.GetString("SaveCustomLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Default&gt;.
        /// </summary>
        internal static string SaveDefaultLocation {
            get {
                return ResourceManager.GetString("SaveDefaultLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Missing location&gt;.
        /// </summary>
        internal static string SaveMissingLocation {
            get {
                return ResourceManager.GetString("SaveMissingLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No program has been selected or there is insufficient information..
        /// </summary>
        internal static string SelectedProgramIsNullOrBlank {
            get {
                return ResourceManager.GetString("SelectedProgramIsNullOrBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected program has ended and can&apos;t be recorded..
        /// </summary>
        internal static string SelectedProgramIsOld {
            get {
                return ResourceManager.GetString("SelectedProgramIsOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program has already begun. It will be recorded as soon as possible..
        /// </summary>
        internal static string SelectedProgramIsRightNow {
            get {
                return ResourceManager.GetString("SelectedProgramIsRightNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;No folder&gt;.
        /// </summary>
        internal static string TaskSchedulerRootFolder {
            get {
                return ResourceManager.GetString("TaskSchedulerRootFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the task is too long. Maximum name length is {0}..
        /// </summary>
        internal static string TooLongTaskName {
            get {
                return ResourceManager.GetString("TooLongTaskName", resourceCulture);
            }
        }
    }
}
