// ==============================================================================
// 
//   Copyright (C) 2014-2020, GitHub/Codeplex user AlphaCentaury
//   All rights reserved.
// 
//     See 'LICENSE.MD' file (or 'license.txt' if missing) in the project root
//     for complete license information.
// 
//   http://www.alphacentaury.org/movistartv
//   https://github.com/AlphaCentaury
// 
// ==============================================================================

namespace IpTviewr.UiServices.Record.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TasksTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TasksTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IpTviewr.UiServices.Record.Properties.TasksTexts", typeof(TasksTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the list..
        /// </summary>
        internal static string CreatingTasksList {
            get {
                return ResourceManager.GetString("CreatingTasksList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recording tasks were found.
        ///
        ///Tip: If you have scheduled recordings use the repair recordings option of the Recordings menú..
        /// </summary>
        internal static string ListEmpty {
            get {
                return ResourceManager.GetString("ListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtaining the list of recording tasks....
        /// </summary>
        internal static string ObtainingListDescription {
            get {
                return ResourceManager.GetString("ObtainingListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to obtaing the list of recording tasks..
        /// </summary>
        internal static string ObtainingListException {
            get {
                return ResourceManager.GetString("ObtainingListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtaining tasks..
        /// </summary>
        internal static string ObtainingTasks {
            get {
                return ResourceManager.GetString("ObtainingTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Unknown).
        /// </summary>
        internal static string RecordingsUnknown {
            get {
                return ResourceManager.GetString("RecordingsUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recording task has been selected..
        /// </summary>
        internal static string SelectionEmpty {
            get {
                return ResourceManager.GetString("SelectionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple selection.
        ///Please select only one task to display its details or to be able to edit the task..
        /// </summary>
        internal static string SelectionMultiple {
            get {
                return ResourceManager.GetString("SelectionMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task details are not available.
        ///Task information might be corrupted or incomplete..
        /// </summary>
        internal static string SelectionNoTaskDetails {
            get {
                return ResourceManager.GetString("SelectionNoTaskDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Unknown).
        /// </summary>
        internal static string TaskNameUnknown {
            get {
                return ResourceManager.GetString("TaskNameUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        internal static string TaskScheduleDaily {
            get {
                return ResourceManager.GetString("TaskScheduleDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly (day).
        /// </summary>
        internal static string TaskScheduleMonthlyDoW {
            get {
                return ResourceManager.GetString("TaskScheduleMonthlyDoW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        internal static string TaskScheduleMontly {
            get {
                return ResourceManager.GetString("TaskScheduleMontly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One time.
        /// </summary>
        internal static string TaskScheduleOneTime {
            get {
                return ResourceManager.GetString("TaskScheduleOneTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immediate.
        /// </summary>
        internal static string TaskScheduleRightNow {
            get {
                return ResourceManager.GetString("TaskScheduleRightNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Unknow: {0}).
        /// </summary>
        internal static string TaskScheduleUnknown {
            get {
                return ResourceManager.GetString("TaskScheduleUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        internal static string TaskScheduleWeekly {
            get {
                return ResourceManager.GetString("TaskScheduleWeekly", resourceCulture);
            }
        }
    }
}
