//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.DvbIpTv.UiServices.Controls.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project.DvbIpTv.UiServices.Controls.Properties.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following characters are not allowed:.
        /// </summary>
        internal static string InputInvalidChar {
            get {
                return ResourceManager.GetString("InputInvalidChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input: character not allowed.
        /// </summary>
        internal static string InputInvalidCharCaption {
            get {
                return ResourceManager.GetString("InputInvalidCharCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule: a value is not valid or allowed.
        /// </summary>
        internal static string RecordingScheduleValidationCaption {
            get {
                return ResourceManager.GetString("RecordingScheduleValidationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total recording time can not exceed {0:N0} days.
        ///Select an earlier date/time to limit the total recording time to less than {0:N0} days..
        /// </summary>
        internal static string RecordingTimeDateTimeSpanMaxValue {
            get {
                return ResourceManager.GetString("RecordingTimeDateTimeSpanMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end date/time can not be earlier than the recording start time..
        /// </summary>
        internal static string RecordingTimeInvalidDateTime {
            get {
                return ResourceManager.GetString("RecordingTimeInvalidDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording time must be at least 60 seconds (1 minute)..
        /// </summary>
        internal static string RecordingTimeInvalidTimeSpan {
            get {
                return ResourceManager.GetString("RecordingTimeInvalidTimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording time: a value is not valid or allowed.
        /// </summary>
        internal static string RecordingTimeValidationCaption {
            get {
                return ResourceManager.GetString("RecordingTimeValidationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 minutes ~ 00:15:00
        ///30 minutes ~ 00:30:00
        ///45 minutes ~ 00:45:00
        ///60 minutes (1 hour) ~ 01:00:00
        ///90 minutes ~ 01:30:00
        ///120 minutes (2 hours) ~ 02:00:00
        ///150 minutes ~ 02:30:00
        ///180 minutes (3 hours) ~ 03:00:00
        ///4 hours ~ 04:00:00
        ///5 hours ~ 05:00:00.
        /// </summary>
        internal static string RecordTimeQuickSettings {
            get {
                return ResourceManager.GetString("RecordTimeQuickSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        internal static string TimeSpanDaysShortLabel {
            get {
                return ResourceManager.GetString("TimeSpanDaysShortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        internal static string TimeSpanHoursShortLabel {
            get {
                return ResourceManager.GetString("TimeSpanHoursShortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        internal static string TimeSpanMinutesShortLabel {
            get {
                return ResourceManager.GetString("TimeSpanMinutesShortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        internal static string TimeSpanSecondsShortLabel {
            get {
                return ResourceManager.GetString("TimeSpanSecondsShortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least a day must be selected for a weekly schedule..
        /// </summary>
        internal static string WeeklyScheduleNoDays {
            get {
                return ResourceManager.GetString("WeeklyScheduleNoDays", resourceCulture);
            }
        }
    }
}
