// ==============================================================================
// 
//   Copyright (C) 2014-2020, GitHub/Codeplex user AlphaCentaury
//   All rights reserved.
// 
//     See 'LICENSE.MD' file (or 'license.txt' if missing) in the project root
//     for complete license information.
// 
//   http://www.alphacentaury.org/movistartv
//   https://github.com/AlphaCentaury
// 
// ==============================================================================

namespace IpTviewr.UiServices.EPG.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EpgRtf {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EpgRtf() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IpTviewr.UiServices.EPG.Properties.EpgRtf", typeof(EpgRtf).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }.
        /// </summary>
        internal static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033
        ///{\fonttbl
        ///{\f0\fnil\fcharset0 Segoe UI;}
        ///{\f1\fnil\fcharset0 Calibri;}
        ///}
        ///\viewkind4\uc1\pard\sa200\sl276\slmult1\lang10.
        /// </summary>
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait. Downloading program extended information....
        /// </summary>
        internal static string LoadingProgramData {
            get {
                return ResourceManager.GetString("LoadingProgramData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to obtain the program extended information..
        /// </summary>
        internal static string NullProgramData {
            get {
                return ResourceManager.GetString("NullProgramData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No synopsis has been provided for this program).
        /// </summary>
        internal static string NullSynopsis {
            get {
                return ResourceManager.GetString("NullSynopsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No title).
        /// </summary>
        internal static string NullTitle {
            get {
                return ResourceManager.GetString("NullTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \f0\fs21 {0}\par.
        /// </summary>
        internal static string ProgramDescription {
            get {
                return ResourceManager.GetString("ProgramDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \f0\fs28\b {0}\b0\par.
        /// </summary>
        internal static string ProgramTitle {
            get {
                return ResourceManager.GetString("ProgramTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \f0\fs28\b {0}\b0\line
        ///\fs25\i {1}\i0\par.
        /// </summary>
        internal static string ProgramTitleOriginalTitle {
            get {
                return ResourceManager.GetString("ProgramTitleOriginalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actor.
        /// </summary>
        internal static string PropertyActor {
            get {
                return ResourceManager.GetString("PropertyActor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actors.
        /// </summary>
        internal static string PropertyActors {
            get {
                return ResourceManager.GetString("PropertyActors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        internal static string PropertyCountries {
            get {
                return ResourceManager.GetString("PropertyCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string PropertyCountry {
            get {
                return ResourceManager.GetString("PropertyCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director.
        /// </summary>
        internal static string PropertyDirector {
            get {
                return ResourceManager.GetString("PropertyDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directors.
        /// </summary>
        internal static string PropertyDirectors {
            get {
                return ResourceManager.GetString("PropertyDirectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producer.
        /// </summary>
        internal static string PropertyProducer {
            get {
                return ResourceManager.GetString("PropertyProducer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producers.
        /// </summary>
        internal static string PropertyProducers {
            get {
                return ResourceManager.GetString("PropertyProducers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string PropertyProductionDate {
            get {
                return ResourceManager.GetString("PropertyProductionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        internal static string PropertyProductionDates {
            get {
                return ResourceManager.GetString("PropertyProductionDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script writer.
        /// </summary>
        internal static string PropertyScripWriter {
            get {
                return ResourceManager.GetString("PropertyScripWriter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script writers.
        /// </summary>
        internal static string PropertyScripWriters {
            get {
                return ResourceManager.GetString("PropertyScripWriters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \b {0}:\b0  {1}\line .
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \par.
        /// </summary>
        internal static string ValuesFooter {
            get {
                return ResourceManager.GetString("ValuesFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \f1\fs21.
        /// </summary>
        internal static string ValuesHeader {
            get {
                return ResourceManager.GetString("ValuesHeader", resourceCulture);
            }
        }
    }
}
