//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.DvbIpTv.UiServices.Configuration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project.DvbIpTv.UiServices.Configuration.Properties.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated domain name &apos;{0}&apos; in &apos;logos/services/domain-mappings.xml&apos;.
        /// </summary>
        internal static string ExceptionLogosDomainMappingsDuplicatedDomain {
            get {
                return ResourceManager.GetString("ExceptionLogosDomainMappingsDuplicatedDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load provider logo file\r\n{0}.
        /// </summary>
        internal static string ExceptionLogosProviderImageLoadError {
            get {
                return ResourceManager.GetString("ExceptionLogosProviderImageLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider logo file not found.
        /// </summary>
        internal static string ExceptionLogosProviderImageNotFound {
            get {
                return ResourceManager.GetString("ExceptionLogosProviderImageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated domain name &apos;{0}&apos; in &apos;logos/providers/provider-mappings.xml&apos;.
        /// </summary>
        internal static string ExceptionLogosProviderMappingsDuplicatedDomain {
            get {
                return ResourceManager.GetString("ExceptionLogosProviderMappingsDuplicatedDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load service logo file\r\n{0}.
        /// </summary>
        internal static string ExceptionLogosServiceImageLoadError {
            get {
                return ResourceManager.GetString("ExceptionLogosServiceImageLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service logo file not found.
        /// </summary>
        internal static string ExceptionLogosServiceImageNotFound {
            get {
                return ResourceManager.GetString("ExceptionLogosServiceImageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated domain name &apos;{0}&apos; in &apos;logos/services/service-mappings.xml&apos;.
        /// </summary>
        internal static string ExceptionLogosServiceMappingsDuplicatedDomain {
            get {
                return ResourceManager.GetString("ExceptionLogosServiceMappingsDuplicatedDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated service name &apos;{0}&apos; in &apos;logos/services/service-mappings.xml&apos; for domain &apos;{1}&apos;.
        /// </summary>
        internal static string ExceptionLogosServiceMappingsDuplicatedService {
            get {
                return ResourceManager.GetString("ExceptionLogosServiceMappingsDuplicatedService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user configuration file &apos;{0}&apos; is invalid or has severe errors.
        ///{1}
        ///
        ///Please verify the XML syntax of the file and correct the detected errors..
        /// </summary>
        internal static string LoadConfigUserConfigValidation {
            get {
                return ResourceManager.GetString("LoadConfigUserConfigValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See exception details (below) for detailed error information..
        /// </summary>
        internal static string LoadConfigUserConfigValidationException {
            get {
                return ResourceManager.GetString("LoadConfigUserConfigValidationException", resourceCulture);
            }
        }
    }
}
