// Copyright (C) 2014-2019, GitHub/Codeplex user AlphaCentaury
// 
// All rights reserved, except those granted by the governing license of this software.
// See 'license.txt' file in the project root for complete license information.
// 
// http://www.alphacentaury.org/movistartv https://github.com/AlphaCentaury

namespace IpTviewr.ChannelList.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InvariantTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InvariantTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IpTviewr.ChannelList.Properties.InvariantTexts", typeof(InvariantTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UA-66146192-4.
        /// </summary>
        internal static string AnalyticsGoogleTrackingId {
            get {
                return ResourceManager.GetString("AnalyticsGoogleTrackingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \bin\debug.
        /// </summary>
        internal static string DebugLocationPath {
            get {
                return ResourceManager.GetString("DebugLocationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\..\..\IpTvRecorderLauncher\bin\debug\.
        /// </summary>
        internal static string DebugRecorderLauncherPath {
            get {
                return ResourceManager.GetString("DebugRecorderLauncherPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to change the applicationt UI language.
        ///The language (&quot;culture&quot;) id may not be valid or not recognized by the system.
        ///Please verify the value of the &apos;ForceUICulture&apos; property in &apos;.config&apos; file.
        ///
        ///No se ha podido cambiar el idioma de la aplicación.
        ///El identificador de idioma (&quot;cultura&quot;) puede no ser válido o no ser reconocido por el sistema.
        ///Verifique el valor de  la propiedad &apos;ForceUICulture&apos; del archivo &apos;.config&apos;.
        /// </summary>
        internal static string ExceptionForceUiCulture {
            get {
                return ResourceManager.GetString("ExceptionForceUiCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IpTvRecorderLauncher.exe.
        /// </summary>
        internal static string ExeRecorderLauncher {
            get {
                return ResourceManager.GetString("ExeRecorderLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://movistartv.alphacentaury.org.
        /// </summary>
        internal static string SplashScreenDefaultStatus {
            get {
                return ResourceManager.GetString("SplashScreenDefaultStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://movistartv.codeplex.com/wikipage?title=Update-v1.5.1010.0.
        /// </summary>
        internal static string UrlCheckForUpdatesManual {
            get {
                return ResourceManager.GetString("UrlCheckForUpdatesManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://movistartv.codeplex.com/documentation.
        /// </summary>
        internal static string UrlDocumentation {
            get {
                return ResourceManager.GetString("UrlDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://movistartv.alphacentaury.org.
        /// </summary>
        internal static string UrlHomePage {
            get {
                return ResourceManager.GetString("UrlHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://movistartv.codeplex.com/workitem/list/basic.
        /// </summary>
        internal static string UrlReportIssue {
            get {
                return ResourceManager.GetString("UrlReportIssue", resourceCulture);
            }
        }
    }
}
