//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IpTviewr.Tools.FirstTimeConfig.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IpTviewr.Tools.FirstTimeConfig.Properties.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang3082{\fonttbl{\f0\fnil\fcharset0 Calibri;}{\f1\fnil\fcharset2 Symbol;}}
        ///{\*\generator Riched20 10.0.18362}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\qc\b\f0\fs28\lang10\tab Help us improve this program!\b0\par
        ///
        ///\pard\sl276\slmult1\qj\fs24 Collecting this information helps us to improve the program through a better understanding of trends and usage patterns of the program, and helps us to try to detect problems and errors.\par
        ///
        ///\pard{\pntext\f1\&apos;B7\tab}{\* [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AppTelemetryHelp {
            get {
                return ResourceManager.GetString("AppTelemetryHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create the configuration file. An error has occurred.
        ///
        ///{0}.
        /// </summary>
        internal static string ConfigurationCreateException {
            get {
                return ResourceManager.GetString("ConfigurationCreateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file(s) successfully created.
        ///First-time configuration process is finished and the application is now ready to be used..
        /// </summary>
        internal static string ConfigurationCreateOk {
            get {
                return ResourceManager.GetString("ConfigurationCreateOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel the configuration of the application?.
        /// </summary>
        internal static string ConfirmUserCancel {
            get {
                return ResourceManager.GetString("ConfirmUserCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENU\x64\SQLServer2005_EMB.msi.
        /// </summary>
        internal static string DownloadEmbFile {
            get {
                return ResourceManager.GetString("DownloadEmbFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENU\x86\SQLServer2005_EMB.msi.
        /// </summary>
        internal static string DownloadEmbFile32bit {
            get {
                return ResourceManager.GetString("DownloadEmbFile32bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} download page has multiple individual downloads. As you&apos;re running a 32-bit version of Windows, make sure to select and install the following file:
        ///&apos;{1}&apos;.
        /// </summary>
        internal static string DownloadFromVendor32bit {
            get {
                return ResourceManager.GetString("DownloadFromVendor32bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} download page has multiple individual downloads. As you&apos;re running a 64-bit version of Windows, make sure to select and install the following file:
        ///&apos;{1}&apos;.
        /// </summary>
        internal static string DownloadFromVendor64bit {
            get {
                return ResourceManager.GetString("DownloadFromVendor64bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENU\SSCERuntime_x64-ENU.exe.
        /// </summary>
        internal static string DownloadSqlCeFile {
            get {
                return ResourceManager.GetString("DownloadSqlCeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENU\SSCERuntime_x86-ENU.exe.
        /// </summary>
        internal static string DownloadSqlCeFile32bit {
            get {
                return ResourceManager.GetString("DownloadSqlCeFile32bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.microsoft.com/en-us/download/details.aspx?id=20101.
        /// </summary>
        internal static string DownloadUrlEmb {
            get {
                return ResourceManager.GetString("DownloadUrlEmb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.microsoft.com/en-us/download/details.aspx?id=22.
        /// </summary>
        internal static string DownloadUrlNet {
            get {
                return ResourceManager.GetString("DownloadUrlNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.microsoft.com/en-us/download/details.aspx?id=30709.
        /// </summary>
        internal static string DownloadUrlSqlCe {
            get {
                return ResourceManager.GetString("DownloadUrlSqlCe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.videolan.org/vlc/index.html.
        /// </summary>
        internal static string DownloadUrlVlc {
            get {
                return ResourceManager.GetString("DownloadUrlVlc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eng;spa.
        /// </summary>
        internal static string DvbIpTv_PreferredLanguages {
            get {
                return ResourceManager.GetString("DvbIpTv_PreferredLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to change the application UI language.
        ///The language (&quot;culture&quot;) id may not be valid or not recognized by the system.
        ///Please verify the value of the &apos;ForceUICulture&apos; program argument.
        ///
        ///No se ha podido cambiar el idioma de la aplicación.
        ///El identificador de idioma (&quot;cultura&quot;) puede no ser válido o no ser reconocido por el sistema.
        ///Verifique el valor del argumento &apos;ForceUICulture&apos; pasado al programa..
        /// </summary>
        internal static string ExceptionForceUiCulture {
            get {
                return ResourceManager.GetString("ExceptionForceUiCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow {0} (part of {2}) {1} inbound connections.
        /// </summary>
        internal static string FirewallDvbIpTvRuleDescription {
            get {
                return ResourceManager.GetString("FirewallDvbIpTvRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to execute the firewall configuration program..
        /// </summary>
        internal static string FirewallException {
            get {
                return ResourceManager.GetString("FirewallException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The firewall configuration has been successfully modified..
        /// </summary>
        internal static string FirewallOk {
            get {
                return ResourceManager.GetString("FirewallOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Firewall configuration change has ben cancelled..
        /// </summary>
        internal static string FirewallUserCancel {
            get {
                return ResourceManager.GetString("FirewallUserCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow VLC media player {0} inbound connections.
        /// </summary>
        internal static string FirewallVlcRuleDescription {
            get {
                return ResourceManager.GetString("FirewallVlcRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K-Lite Media Player Classic.
        /// </summary>
        internal static string GetTvPlayersMpc {
            get {
                return ResourceManager.GetString("GetTvPlayersMpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K-Lite Media Player Classic (32 bits).
        /// </summary>
        internal static string GetTvPlayersMpcX86 {
            get {
                return ResourceManager.GetString("GetTvPlayersMpcX86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VLC.
        /// </summary>
        internal static string GetTvPlayersVlc {
            get {
                return ResourceManager.GetString("GetTvPlayersVlc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VLC (no new window).
        /// </summary>
        internal static string GetTvPlayersVlcSameWindow {
            get {
                return ResourceManager.GetString("GetTvPlayersVlcSameWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VLC (no new window - 32 bits).
        /// </summary>
        internal static string GetTvPlayersVlcSameWindowX86 {
            get {
                return ResourceManager.GetString("GetTvPlayersVlcSameWindowX86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VLC (32 bits).
        /// </summary>
        internal static string GetTvPlayersVlcX86 {
            get {
                return ResourceManager.GetString("GetTvPlayersVlcX86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine if the Microsoft® Exception Message Box component is installed.
        ///
        ///{0}.
        /// </summary>
        internal static string IsEmbInstalledException {
            get {
                return ResourceManager.GetString("IsEmbInstalledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft® Exception Message Box component is not installed on this machine..
        /// </summary>
        internal static string IsEmbInstalledNotInstalled {
            get {
                return ResourceManager.GetString("IsEmbInstalledNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation of the Microsoft® Exception Message Box component (v{0}) has been verified..
        /// </summary>
        internal static string IsEmbInstalledOk {
            get {
                return ResourceManager.GetString("IsEmbInstalledOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine the installed version of Microsoft® .NET Framework.
        ///
        ///{0}.
        /// </summary>
        internal static string IsNetInstalledException {
            get {
                return ResourceManager.GetString("IsNetInstalledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework v3.5 &apos;{0}&apos; registry value is less than {1}..
        /// </summary>
        internal static string IsNetInstalledKeyValueLessThan {
            get {
                return ResourceManager.GetString("IsNetInstalledKeyValueLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework v3.5 &apos;{0}&apos; registry value not found..
        /// </summary>
        internal static string IsNetInstalledKeyValueNotFound {
            get {
                return ResourceManager.GetString("IsNetInstalledKeyValueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft® .NET Framework v3.5 is not installed on this machine..
        /// </summary>
        internal static string IsNetInstalledNotInstalled {
            get {
                return ResourceManager.GetString("IsNetInstalledNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation of Microsoft® .NET Framework v3.5 Service Pack 1 (or greater) has been verified..
        /// </summary>
        internal static string IsNetInstalledOk {
            get {
                return ResourceManager.GetString("IsNetInstalledOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine if the Microsoft® SQL Server® Compact 4.0 SP1 is installed.
        ///
        ///{0}.
        /// </summary>
        internal static string IsSqlCeInstalledException {
            get {
                return ResourceManager.GetString("IsSqlCeInstalledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft® SQL Server® Compact 4.0 SP1 is not installed on this machine..
        /// </summary>
        internal static string IsSqlCeInstalledNotInstalled {
            get {
                return ResourceManager.GetString("IsSqlCeInstalledNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation of Microsoft® SQL Server® Compact Edition 4.0 SP1 (v{0}) has been verified..
        /// </summary>
        internal static string IsSqlCeInstalledOk {
            get {
                return ResourceManager.GetString("IsSqlCeInstalledOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine if the VLC player is properly installed.
        ///
        ///{0}.
        /// </summary>
        internal static string IsVlcInstalledException {
            get {
                return ResourceManager.GetString("IsVlcInstalledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VLC executable file not found at &apos;{0}&apos;..
        /// </summary>
        internal static string IsVlcInstalledNotInstalled {
            get {
                return ResourceManager.GetString("IsVlcInstalledNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation of the VLC player (version {0}) and its library file (version {1}) has been verified..
        /// </summary>
        internal static string IsVlcInstalledOk {
            get {
                return ResourceManager.GetString("IsVlcInstalledOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VLC player version {0} (or greater) is not installed on this machine.
        ///Currently installed version is {1}..
        /// </summary>
        internal static string IsVlcInstalledVersion {
            get {
                return ResourceManager.GetString("IsVlcInstalledVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VLC library file not found at &apos;{0}&apos;..
        /// </summary>
        internal static string IsVlcLibInstalledNotInstalled {
            get {
                return ResourceManager.GetString("IsVlcLibInstalledNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VLC library version {0} (or greater) is not installed on this machine.
        ///Currently installed version is {1}..
        /// </summary>
        internal static string IsVlcLibInstalledVersion {
            get {
                return ResourceManager.GetString("IsVlcLibInstalledVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to execute program &apos;{0}&apos;.
        ///
        ///{1}.
        /// </summary>
        internal static string LaunchProgramException {
            get {
                return ResourceManager.GetString("LaunchProgramException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} setup process has finished with an error (code: {1:N0}).
        ///
        ///Try running the setup program again..
        /// </summary>
        internal static string LaunchSetupError {
            get {
                return ResourceManager.GetString("LaunchSetupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to execute the setup program &apos;{0}&apos; for &apos;{1}.
        ///
        ///{2}.
        /// </summary>
        internal static string LaunchSetupException {
            get {
                return ResourceManager.GetString("LaunchSetupException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} setup process has finished.
        ///
        ///Click &apos;Verify&apos; to test the proper installation of the component..
        /// </summary>
        internal static string LaunchSetupSuccess {
            get {
                return ResourceManager.GetString("LaunchSetupSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is an optional feature of Windows 10 and is not installed.
        ///Windows will now ask you if you wish to install it.
        ///
        ///1. Select &apos;Download and install this feature&apos;.
        ///2. Follow the wizard to completion.
        ///3. Press &apos;Verify...&apos; to check if {0} is properly installed..
        /// </summary>
        internal static string NetFxRequired {
            get {
                return ResourceManager.GetString("NetFxRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install as Windows optional feature.
        /// </summary>
        internal static string NextFxWindows10Setup {
            get {
                return ResourceManager.GetString("NextFxWindows10Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VLC player|vlc.exe|Programs|*.exe.
        /// </summary>
        internal static string OpenFileVlcFilter {
            get {
                return ResourceManager.GetString("OpenFileVlcFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the location of the VLC player.
        /// </summary>
        internal static string OpenFileVlcTitle {
            get {
                return ResourceManager.GetString("OpenFileVlcTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open browser for URL &apos;{0}&apos;.
        ///
        ///{1}.
        /// </summary>
        internal static string OpenUrlError {
            get {
                return ResourceManager.GetString("OpenUrlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;user-config.xml&apos; file already exists.
        ///If you overwrite the file all custom configurations will be lost.
        ///
        ///Do you want to overwrite the existing file?.
        /// </summary>
        internal static string OverwriteXmlConfigFile {
            get {
                return ResourceManager.GetString("OverwriteXmlConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPTViewr: virtual decoder for movistar+.
        /// </summary>
        internal static string ProductFullName {
            get {
                return ResourceManager.GetString("ProductFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPTViewr for movistar+.
        /// </summary>
        internal static string ProductMainProgramName {
            get {
                return ResourceManager.GetString("ProductMainProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v1.5 “Kruger 60” beta 1 SP1.
        /// </summary>
        internal static string ProductShortName {
            get {
                return ResourceManager.GetString("ProductShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang3082{\fonttbl{\f0\fswiss\fprq2\fcharset0 Calibri;}{\f1\fnil\fcharset0 Calibri;}{\f2\fnil\fcharset2 Symbol;}}
        ///{\*\generator Riched20 10.0.18362}\viewkind4\uc1 
        ///\pard\nowidctlpar\sl276\slmult1\qj\f0\fs24\lang10 This program \b requires\b0 , necessarily, having contracted \b a movistar+ subscription\b0  in either fiber (FFTH) or DSL mode in Spain. \b The satellite connection is not supported\b0 .\par
        ///
        ///\pard{\pntext\f2\&apos;B7\tab}{\*\pn\pnlvlblt\pnf2\pnindent0{\p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Readme {
            get {
                return ResourceManager.GetString("Readme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing {0}....
        /// </summary>
        internal static string RedistSetupInstalling {
            get {
                return ResourceManager.GetString("RedistSetupInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movies.
        /// </summary>
        internal static string SaveLocationMoviesFolder {
            get {
                return ResourceManager.GetString("SaveLocationMoviesFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movies.
        /// </summary>
        internal static string SaveLocationMoviesName {
            get {
                return ResourceManager.GetString("SaveLocationMoviesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series.
        /// </summary>
        internal static string SaveLocationSeriesFolder {
            get {
                return ResourceManager.GetString("SaveLocationSeriesFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series.
        /// </summary>
        internal static string SaveLocationSeriesName {
            get {
                return ResourceManager.GetString("SaveLocationSeriesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a default folder for saving TV recordings..
        /// </summary>
        internal static string SelectFolderSaveDescription {
            get {
                return ResourceManager.GetString("SelectFolderSaveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPTViewr folder.
        /// </summary>
        internal static string TaskSchedulerFolderDvbIpTv {
            get {
                return ResourceManager.GetString("TaskSchedulerFolderDvbIpTv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program data recollection.
        /// </summary>
        internal static string TelemetryHelpCaption {
            get {
                return ResourceManager.GetString("TelemetryHelpCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine if the VLC player is properly installed.
        ///
        ///{0}.
        /// </summary>
        internal static string TestVlcInstallationException {
            get {
                return ResourceManager.GetString("TestVlcInstallationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VLC player has been successfully launched..
        /// </summary>
        internal static string TestVlcInstallationOk {
            get {
                return ResourceManager.GetString("TestVlcInstallationOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application is not properly configured and will not run.
        ///To properly configure the application at a later time, please run this wizard again..
        /// </summary>
        internal static string WizardEndTextAbort {
            get {
                return ResourceManager.GetString("WizardEndTextAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application is not properly configured and will not run.
        ///To properly configure the application at a later time, please run this wizard again..
        /// </summary>
        internal static string WizardEndTextCancel {
            get {
                return ResourceManager.GetString("WizardEndTextCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First-time configuration process is finished and the application is now ready to be used..
        /// </summary>
        internal static string WizardEndTextOk {
            get {
                return ResourceManager.GetString("WizardEndTextOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not perform the initial configuration of the application..
        /// </summary>
        internal static string WizardEndTitleAbort {
            get {
                return ResourceManager.GetString("WizardEndTitleAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first-time configuration of the application has been cancelled..
        /// </summary>
        internal static string WizardEndTitleCancel {
            get {
                return ResourceManager.GetString("WizardEndTitleCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file(s) successfully created..
        /// </summary>
        internal static string WizardEndTitleOk {
            get {
                return ResourceManager.GetString("WizardEndTitleOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not perform the initial configuration of the application.
        ///
        ///The application is not properly configured and will not run.
        ///To properly configure the application at a later time, please run this wizard again..
        /// </summary>
        internal static string WizardResultAborted {
            get {
                return ResourceManager.GetString("WizardResultAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first-time configuration of the application has been cancelled.
        ///
        ///The application is not properly configured and will not run.
        ///To properly configure the application at a later time, please run this wizard again..
        /// </summary>
        internal static string WizardResultUserCancel {
            get {
                return ResourceManager.GetString("WizardResultUserCancel", resourceCulture);
            }
        }
    }
}
