//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.DvbIpTv.ChannelList.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project.DvbIpTv.ChannelList.Properties.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to obtain the list of TV channels/services.
        /// </summary>
        internal static string BroadcastListUnableRefresh {
            get {
                return ResourceManager.GetString("BroadcastListUnableRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtaining list of TV channels/services....
        /// </summary>
        internal static string BroadcastObtainingList {
            get {
                return ResourceManager.GetString("BroadcastObtainingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing and extracting the list of TV channels/services....
        /// </summary>
        internal static string BroadcastParsingList {
            get {
                return ResourceManager.GetString("BroadcastParsingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties of the TV channel/service.
        /// </summary>
        internal static string BroadcastServiceProperties {
            get {
                return ResourceManager.GetString("BroadcastServiceProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait. Canceling download....
        /// </summary>
        internal static string CancellingDownloadOperation {
            get {
                return ResourceManager.GetString("CancellingDownloadOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movistar TV DVB-IPTV channel/services list (beta 1.0.2 “Wolf 424”).
        /// </summary>
        internal static string ChannelListFormCaption {
            get {
                return ResourceManager.GetString("ChannelListFormCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data reception is complete.
        /// </summary>
        internal static string CompletedDownloadDataReception {
            get {
                return ResourceManager.GetString("CompletedDownloadDataReception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The extension of the file of the recording can not be empty.
        ///Please specify a file extension..
        /// </summary>
        internal static string DialogRecordChannelEmptyFileExtension {
            get {
                return ResourceManager.GetString("DialogRecordChannelEmptyFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the file of the recording can not be empty.
        ///Please specify a name..
        /// </summary>
        internal static string DialogRecordChannelEmptyFileName {
            get {
                return ResourceManager.GetString("DialogRecordChannelEmptyFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the task can not be empty.
        ///Please specify a name..
        /// </summary>
        internal static string DialogRecordChannelEmptyTaskName {
            get {
                return ResourceManager.GetString("DialogRecordChannelEmptyTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A save location has not been selected.
        ///Please select one or browse for a folder..
        /// </summary>
        internal static string DialogRecordChannelNoSaveLocation {
            get {
                return ResourceManager.GetString("DialogRecordChannelNoSaveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Custom location&gt;.
        /// </summary>
        internal static string DialogRecordSaveCustomLocation {
            get {
                return ResourceManager.GetString("DialogRecordSaveCustomLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Default&gt;.
        /// </summary>
        internal static string DialogRecordSaveDefaultLocation {
            get {
                return ResourceManager.GetString("DialogRecordSaveDefaultLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Missing location&gt;.
        /// </summary>
        internal static string DialogRecordSaveMissingLocation {
            get {
                return ResourceManager.GetString("DialogRecordSaveMissingLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has ocurred while fetching data.
        /// </summary>
        internal static string DvbStpDownloadHelperExceptionCaption {
            get {
                return ResourceManager.GetString("DvbStpDownloadHelperExceptionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request cancelled.
        /// </summary>
        internal static string DvbStpDownloadHelperUserCancelledCaption {
            get {
                return ResourceManager.GetString("DvbStpDownloadHelperUserCancelledCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launches {0} player to view DVB-IPTV channel &apos;{1}&apos;.
        /// </summary>
        internal static string ExternalPlayerShortcutDescription {
            get {
                return ResourceManager.GetString("ExternalPlayerShortcutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string MulticastScannerDlgActive {
            get {
                return ResourceManager.GetString("MulticastScannerDlgActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to “Dead”.
        /// </summary>
        internal static string MulticastScannerDlgDead {
            get {
                return ResourceManager.GetString("MulticastScannerDlgDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MulticastScannerDlgError {
            get {
                return ResourceManager.GetString("MulticastScannerDlgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped.
        /// </summary>
        internal static string MulticastScannerDlgSkipped {
            get {
                return ResourceManager.GetString("MulticastScannerDlgSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string MulticastScannerDlgTotal {
            get {
                return ResourceManager.GetString("MulticastScannerDlgTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan has been cancelled by the user.
        /// </summary>
        internal static string MulticastServiceScanningCancelled {
            get {
                return ResourceManager.GetString("MulticastServiceScanningCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait. Canceling scan....
        /// </summary>
        internal static string MulticastServiceScanningCancelling {
            get {
                return ResourceManager.GetString("MulticastServiceScanningCancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan is complete.
        /// </summary>
        internal static string MulticastServiceScanningCompleted {
            get {
                return ResourceManager.GetString("MulticastServiceScanningCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred during the scan and has been aborted.
        /// </summary>
        internal static string MulticastServiceScanningError {
            get {
                return ResourceManager.GetString("MulticastServiceScanningError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start the application.
        /// </summary>
        internal static string MyAppCtxExceptionCaption {
            get {
                return ResourceManager.GetString("MyAppCtxExceptionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred while initializating the application..
        /// </summary>
        internal static string MyAppCtxExceptionMsg {
            get {
                return ResourceManager.GetString("MyAppCtxExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application configuration error.
        /// </summary>
        internal static string MyAppCtxInitializationErrorCaption {
            get {
                return ResourceManager.GetString("MyAppCtxInitializationErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading application configuration....
        /// </summary>
        internal static string MyAppCtxLoadingConfig {
            get {
                return ResourceManager.GetString("MyAppCtxLoadingConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading user configuration and preferences....
        /// </summary>
        internal static string MyAppCtxLoadingUserConfig {
            get {
                return ResourceManager.GetString("MyAppCtxLoadingUserConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting application....
        /// </summary>
        internal static string MyAppCtxStarting {
            get {
                return ResourceManager.GetString("MyAppCtxStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while processing your request.
        /// </summary>
        internal static string MyAppHandleExceptionDefaultCaption {
            get {
                return ResourceManager.GetString("MyAppHandleExceptionDefaultCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occured while loading the application configuration.
        ///The application will now end..
        /// </summary>
        internal static string MyAppLoadConfigException {
            get {
                return ResourceManager.GetString("MyAppLoadConfigException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application configuration error.
        /// </summary>
        internal static string MyAppLoadConfigExceptionCaption {
            get {
                return ResourceManager.GetString("MyAppLoadConfigExceptionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the &apos;Recorder Launcher&apos; program at &apos;{0}&apos;..
        /// </summary>
        internal static string MyAppRecorderLauncherNotFound {
            get {
                return ResourceManager.GetString("MyAppRecorderLauncherNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Description has not been provided&gt;.
        /// </summary>
        internal static string NotProvidedDescription {
            get {
                return ResourceManager.GetString("NotProvidedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Not provided&gt;.
        /// </summary>
        internal static string NotProvidedValue {
            get {
                return ResourceManager.GetString("NotProvidedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No service provider has been selected.
        /// </summary>
        internal static string NotSelectedServiceProvider {
            get {
                return ResourceManager.GetString("NotSelectedServiceProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} [{1:yyyy\-MM\-dd} {2:HH\-mm\-ss}].
        /// </summary>
        internal static string RecordTaskNameSuggestedNameFormat {
            get {
                return ResourceManager.GetString("RecordTaskNameSuggestedNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to obtain the list of service providers.
        /// </summary>
        internal static string SPListUnableRefresh {
            get {
                return ResourceManager.GetString("SPListUnableRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtaining the list of service providers....
        /// </summary>
        internal static string SPObtainingList {
            get {
                return ResourceManager.GetString("SPObtainingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing and extracting the list of providers....
        /// </summary>
        internal static string SPParsingList {
            get {
                return ResourceManager.GetString("SPParsingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties of the service provider.
        /// </summary>
        internal static string SPProperties {
            get {
                return ResourceManager.GetString("SPProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;No folder&gt;.
        /// </summary>
        internal static string TaskSchedulerRootFolder {
            get {
                return ResourceManager.GetString("TaskSchedulerRootFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to cancel.
        /// </summary>
        internal static string UnableCancelDownloadCaption {
            get {
                return ResourceManager.GetString("UnableCancelDownloadCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to cancel right now. Please try again in a few seconds.
        ///
        ///The operation has been scheduled and cannot be cancelled until it has started..
        /// </summary>
        internal static string UnableCancelDownloadMessage {
            get {
                return ResourceManager.GetString("UnableCancelDownloadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The refreshing of the list has been cancelled by the user..
        /// </summary>
        internal static string UserCancelListRefresh {
            get {
                return ResourceManager.GetString("UserCancelListRefresh", resourceCulture);
            }
        }
    }
}
