//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.IpTv.Services.Record.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project.IpTv.Services.Record.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1DCDA40A-A9D5-4CF3-B3C5-971B8811F127: IPTV Record Task
        ///TaskId: {0}
        ///Database: {1}.
        /// </summary>
        internal static string DefinitionRegistrationInfo_Documentation {
            get {
                return ResourceManager.GetString("DefinitionRegistrationInfo_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1DCDA40A-A9D5-4CF3-B3C5-971B8811F127: IPTV Record Task.
        /// </summary>
        internal static string DefinitionRegistrationInfo_Documentation_Begins {
            get {
                return ResourceManager.GetString("DefinitionRegistrationInfo_Documentation_Begins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Id: {0}
        ///Task file: {1}.
        /// </summary>
        internal static string DefinitionRegistrationInfo_DocumentationV1 {
            get {
                return ResourceManager.GetString("DefinitionRegistrationInfo_DocumentationV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Id:.
        /// </summary>
        internal static string DefinitionRegistrationInfo_DocumentationV1_Begins {
            get {
                return ResourceManager.GetString("DefinitionRegistrationInfo_DocumentationV1_Begins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string DefinitionRegistrationInfo_Source {
            get {
                return ResourceManager.GetString("DefinitionRegistrationInfo_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecordTasks.sdf.
        /// </summary>
        internal static string RecordTasksDatabaseFile {
            get {
                return ResourceManager.GetString("RecordTasksDatabaseFile", resourceCulture);
            }
        }
    }
}
