// ==============================================================================
// 
//   Copyright (C) 2014-2020, GitHub/Codeplex user AlphaCentaury
//   All rights reserved.
// 
//     See 'LICENSE.MD' file (or 'license.txt' if missing) in the project root
//     for complete license information.
// 
//   http://www.alphacentaury.org/movistartv
//   https://github.com/AlphaCentaury
// 
// ==============================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IpTviewr.UiServices.Configuration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InvariantTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InvariantTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IpTviewr.UiServices.Configuration.Properties.InvariantTexts", typeof(InvariantTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVB-IPTV.
        /// </summary>
        internal static string DefaultDomainNameProviderLogo {
            get {
                return ResourceManager.GetString("DefaultDomainNameProviderLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPTV.
        /// </summary>
        internal static string DefaultDomainNameServiceLogo {
            get {
                return ResourceManager.GetString("DefaultDomainNameServiceLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to domain-mappings.xml.
        /// </summary>
        internal static string FileLogoDomainMappings {
            get {
                return ResourceManager.GetString("FileLogoDomainMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to provider-mappings.xml.
        /// </summary>
        internal static string FileLogoProviderMappings {
            get {
                return ResourceManager.GetString("FileLogoProviderMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service-mappings.xml.
        /// </summary>
        internal static string FileLogoServiceMappings {
            get {
                return ResourceManager.GetString("FileLogoServiceMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cache.
        /// </summary>
        internal static string FolderCache {
            get {
                return ResourceManager.GetString("FolderCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logos.
        /// </summary>
        internal static string FolderLogosCache {
            get {
                return ResourceManager.GetString("FolderLogosCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to providers.
        /// </summary>
        internal static string FolderLogosProviders {
            get {
                return ResourceManager.GetString("FolderLogosProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logos.
        /// </summary>
        internal static string FolderLogosRoot {
            get {
                return ResourceManager.GetString("FolderLogosRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to services.
        /// </summary>
        internal static string FolderLogosServices {
            get {
                return ResourceManager.GetString("FolderLogosServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modules.
        /// </summary>
        internal static string FolderModules {
            get {
                return ResourceManager.GetString("FolderModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to record-tasks.
        /// </summary>
        internal static string FolderRecordTasks {
            get {
                return ResourceManager.GetString("FolderRecordTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}::{1}.
        /// </summary>
        internal static string FormatServiceLogoKey {
            get {
                return ResourceManager.GetString("FormatServiceLogoKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IpTvRecorderLauncher.exe.
        /// </summary>
        internal static string RecorderLauncher {
            get {
                return ResourceManager.GetString("RecorderLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software\AlphaCentaury.org\IPTViewr\movistar+\v{0}.
        /// </summary>
        internal static string RegistryKey_Root {
            get {
                return ResourceManager.GetString("RegistryKey_Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstTimeConfig.
        /// </summary>
        internal static string RegistryValue_FirstTimeConfig {
            get {
                return ResourceManager.GetString("RegistryValue_FirstTimeConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.Base.
        /// </summary>
        internal static string RegistryValue_Folder_Base {
            get {
                return ResourceManager.GetString("RegistryValue_Folder_Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.Install.
        /// </summary>
        internal static string RegistryValue_Folder_Install {
            get {
                return ResourceManager.GetString("RegistryValue_Folder_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        internal static string RegistryValue_Installed {
            get {
                return ResourceManager.GetString("RegistryValue_Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;any&gt;.
        /// </summary>
        internal static string ServiceNameAny {
            get {
                return ResourceManager.GetString("ServiceNameAny", resourceCulture);
            }
        }
    }
}
